LOCK TABLES `User` WRITE,`UserPreferences` WRITE;
INSERT INTO `User` (`idUser`, `user`, `email`, `hash`, `type`, `created`, `updated`, `updatedBy`) VALUES (1,'admin','gm@localhost','$2y$10$rtE03IHT3GfbYm8CJEFO8udE34zgP7BePodqgym/KjcJcavqdG/W6','administrator','2020-05-08 17:23',NULL,'server');
#INSERT INTO `User` (`idUser`, `user`, `email`, `hash`, `created`, `updated`, `updatedBy`) VALUES (1,'gm','gm@localhost',CONCAT('{SHA}',to_base64(unhex(sha1('hdywtdt')))),'2020-05-08 17:23',NULL,'server');
INSERT INTO `User` (`idUser`, `user`, `email`, `hash`, `type`, `created`, `updated`, `updatedBy`) VALUES (2,'gm','gm@localhost','$2y$10$rtE03IHT3GfbYm8CJEFO8udE34zgP7BePodqgym/KjcJcavqdG/W6','standard','2020-05-08 17:23',NULL,'server');
INSERT INTO `UserPreferences` (`idUser`, `userName`, `selectColor`, `mapScale`, `updated`, `updatedBy`) VALUES (1,'Local Game Master','#ff9900',1.0,NULL,'server');
#INSERT INTO `User` (`idUser`, `user`, `email`, `hash`, `created`, `updated`, `updatedBy`) VALUES (2,'pc','pc@localhost',CONCAT('{SHA}',to_base64(unhex(sha1('letsplay')))),'2020-05-08 17:23',NULL,'server');
INSERT INTO `User` (`idUser`, `user`, `email`, `hash`, `type`, `created`, `updated`, `updatedBy`) VALUES (3,'pc','pc@localhost','$2y$10$TBqi/txEYuw00ebwB3rlD.oFlK3ZZRhyQx7bDrNT9cUxJsIyvgUP.','standard','2020-05-08 17:23',NULL,'server');
INSERT INTO `UserPreferences` (`idUser`, `userName`, `selectColor`, `mapScale`, `updated`, `updatedBy`) VALUES (2,'Local Player','#ff66ff',1.0,NULL,'server');
UNLOCK TABLES;
LOCK TABLES `User` READ, `AdventureAuthority` WRITE, `Adventure` READ;
INSERT INTO `AdventureAuthority` (`idUser`,`idAdventure`,`canView`,`canControl`) VALUES (2,1,True,True);
INSERT INTO `AdventureAuthority` (`idUser`,`idAdventure`,`canView`,`canControl`) VALUES (3,1,True,False);
UNLOCK TABLES;
LOCK TABLES `User` READ, `MapAuthority` WRITE, `Map` READ;
INSERT INTO `MapAuthority` (`idUser`,`idMap`,`canView`) VALUES (3,1,False);
UNLOCK TABLES;
LOCK TABLES `User` READ, `RoleAuthority` WRITE, `Role` READ;
INSERT INTO `RoleAuthority` (`idUser`,`idRole`,`canControl`) VALUES (3,1,True);
UNLOCK TABLES;